"""
Authenticated security-event monitoring API for Mama AI.

The API exposes only sanitized security-event records. Authentication
tokens, raw client addresses, API keys, passwords, cookies, and other
secret values are never returned by these endpoints.
"""

from __future__ import annotations

import secrets
from collections import Counter
from typing import Annotated, Any

from fastapi import (
    APIRouter,
    Depends,
    HTTPException,
    Query,
)
from fastapi.encoders import jsonable_encoder

from app.api.auth import (
    configured_owner_id,
    require_principal,
    resolve_requested_owner,
)
from app.database.security_event_db import (
    security_event_store,
)


router = APIRouter(
    prefix="/security",
    tags=["Security"],
    dependencies=[
        Depends(require_principal),
    ],
)


def _clean_event_id(
    event_id: str,
) -> str:
    if not isinstance(event_id, str):
        raise HTTPException(
            status_code=400,
            detail=(
                "Security event ID must be text."
            ),
        )

    event_id = event_id.strip()

    if not event_id:
        raise HTTPException(
            status_code=400,
            detail=(
                "Security event ID cannot be empty."
            ),
        )

    return event_id


def _event_is_accessible(
    record: dict[str, Any],
    owner_id: str,
) -> bool:
    """
    Return whether one record is visible to the authenticated owner.

    Ownerless events are generated by request-level controls such as
    rate limiting before a principal is established. They remain
    visible to the current single-owner deployment.
    """

    record_owner = record.get(
        "owner_id"
    )

    if record_owner is None:
        return True

    if not isinstance(record_owner, str):
        return False

    record_owner = record_owner.strip()

    return bool(
        record_owner
        and secrets.compare_digest(
            record_owner,
            owner_id,
        )
    )


def _validated_owner(
    requested_owner_id: str | None,
) -> str:
    return resolve_requested_owner(
        requested_owner_id
    )


@router.get("/events")
def list_security_events(
    event_type: str | None = None,
    severity: str | None = None,
    client_ref: str | None = None,
    owner_id: str | None = None,
    limit: Annotated[
        int,
        Query(ge=1, le=1000),
    ] = 100,
) -> dict[str, Any]:
    """
    Return recent sanitized security events visible to the owner.

    The optional owner_id parameter exists only for legacy clients. It
    must match the authenticated owner and cannot broaden visibility.
    """

    authenticated_owner = (
        _validated_owner(
            owner_id
        )
    )

    fetch_limit = min(
        max(
            limit * 10,
            limit,
        ),
        1000,
    )

    try:
        records = (
            security_event_store.list(
                event_type=event_type,
                severity=severity,
                client_ref=client_ref,
                limit=fetch_limit,
            )
        )

    except (TypeError, ValueError) as exc:
        raise HTTPException(
            status_code=400,
            detail=str(exc),
        ) from exc

    visible_records = [
        record
        for record in records
        if _event_is_accessible(
            record,
            authenticated_owner,
        )
    ][:limit]

    return {
        "success": True,
        "count": len(
            visible_records
        ),
        "order": "newest_first",
        "events": jsonable_encoder(
            visible_records
        ),
    }


@router.get("/events/summary")
def security_event_summary(
    event_type: str | None = None,
    severity: str | None = None,
    owner_id: str | None = None,
) -> dict[str, Any]:
    """
    Summarize up to the newest 1,000 visible security events.

    A bounded summary prevents an unbounded in-memory query while the
    project uses the current single-process SQLite architecture.
    """

    authenticated_owner = (
        _validated_owner(
            owner_id
        )
    )

    try:
        records = (
            security_event_store.list(
                event_type=event_type,
                severity=severity,
                limit=1000,
            )
        )

    except (TypeError, ValueError) as exc:
        raise HTTPException(
            status_code=400,
            detail=str(exc),
        ) from exc

    visible_records = [
        record
        for record in records
        if _event_is_accessible(
            record,
            authenticated_owner,
        )
    ]

    by_event_type = Counter(
        str(
            record.get(
                "event_type",
                "unknown",
            )
        )
        for record in visible_records
    )

    by_severity = Counter(
        str(
            record.get(
                "severity",
                "unknown",
            )
        )
        for record in visible_records
    )

    status_codes = Counter(
        str(
            record["status_code"]
        )
        for record in visible_records
        if record.get(
            "status_code"
        ) is not None
    )

    latest_created_at = (
        visible_records[0].get(
            "created_at"
        )
        if visible_records
        else None
    )

    return {
        "success": True,
        "summary": {
            "total": len(
                visible_records
            ),
            "sample_limit": 1000,
            "sample_truncated": (
                len(records) >= 1000
            ),
            "latest_created_at": (
                latest_created_at
            ),
            "by_event_type": dict(
                sorted(
                    by_event_type.items()
                )
            ),
            "by_severity": dict(
                sorted(
                    by_severity.items()
                )
            ),
            "by_status_code": dict(
                sorted(
                    status_codes.items()
                )
            ),
        },
    }


@router.get("/events/{event_id}")
def get_security_event(
    event_id: str,
) -> dict[str, Any]:
    """Return one sanitized security event visible to the owner."""

    event_id = _clean_event_id(
        event_id
    )
    authenticated_owner = (
        configured_owner_id()
    )

    try:
        record = (
            security_event_store.get(
                event_id
            )
        )

    except (TypeError, ValueError) as exc:
        raise HTTPException(
            status_code=400,
            detail=str(exc),
        ) from exc

    if (
        record is None
        or not _event_is_accessible(
            record,
            authenticated_owner,
        )
    ):
        raise HTTPException(
            status_code=404,
            detail=(
                "Security event was not found: "
                f"{event_id}"
            ),
        )

    return {
        "success": True,
        "event": jsonable_encoder(
            record
        ),
    }


__all__ = [
    "get_security_event",
    "list_security_events",
    "router",
    "security_event_summary",
]
